### ISSUE TITLE
Tasty bytes setup link is internal

### ISSUE THREAD

**Issue by sfc-gh-vtimofeenko** [sfc-gh-mkobel/hybrid-table-quickstart#1]
[This line](https://github.com/sfc-gh-mkobel/hybrid-table-quickstart/blob/2fd944f0d62fbf03228e32f5367629f8640ea2c3/README.md?plain=1#L49) refers to tasty bytes, which AFAIK require manual share of the data and the link to the setup is private

**Comment by sfc-gh-mkobel** [comment]
Nice catch
